---
- name: "Install telegraf"
  yum:
    name: "{{telegraf_url}}"
    state: present
- name: "Telegraf config"
  template:
    src: templates/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: "Start Telegraf"
  service:
    name: "telegraf"
    state: restarted