---
- name: "Install grafana"
  yum:
    name: "{{grafana_url}}"
    state: present
- copy:
    src: templates/grafana.ini
    dest: /etc/grafana/grafana.ini
- service:
    name: grafana-server
    state: restarted
    
- name: Create influxdb datasource
  grafana_datasource:
    name: "my-influx"
    grafana_url: "https://127.0.0.1:8080"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://localhost:8086"
    database: "metrics"